#!/usr/bash

set -ev

code --install-extension EditorConfig.EditorConfig
code --install-extension SirTori.indenticator
code --install-extension anseki.vscode-color
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension Compulim.vscode-clock
code --install-extension dakshmiglani.hex-to-rgba
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension DotJoshJohnson.xml
code --install-extension dougdoan.theme-argonaut
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension Equinusocio.vsc-material-theme
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-todo-plus
code --install-extension felixfbecker.php-debug
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-complete-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.vscode-mysql
code --install-extension GrapeCity.gc-excelviewer
code --install-extension huangdongsheng.HdsCppSnippets
code --install-extension humao.rest-client
code --install-extension idrabenia.solidity-solhint
code --install-extension JuanBlanco.solidity
code --install-extension karyfoundation.theme-karyfoundation-themes
code --install-extension kokororin.vscode-phpfmt
code --install-extension mikestead.dotenv
code --install-extension ms-python.python
code --install-extension ms-vscode.atom-keybindings
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.Go
code --install-extension ms-vscode.sublime-keybindings
code --install-extension ms-vscode.Theme-TomorrowKit
code --install-extension myax.appidocsnippets
code --install-extension naumovs.color-highlight
code --install-extension oguhpereira.spotify-color-theme
code --install-extension PeterJausovec.vscode-docker
code --install-extension redhat.vscode-yaml
code --install-extension robertohuertasm.vscode-icons
code --install-extension Sujan.code-blue
code --install-extension tomoki1207.pdf
code --install-extension vangware.dark-plus-material
code --install-extension vip32bit.theme-monokai-black
code --install-extension WallabyJs.quokka-vscode
code --install-extension wmaurer.change-case
code --install-extension xabikos.JavaScriptSnippets
code --install-extension xabikos.ReactSnippets
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.Material-theme
